In [1]:
import numpy as np 
import sympy as sy

# Lecture 28: Two-by-Two and Three-by-Three Determinants

Let $A$ and $B$ be $2\times 2$ matrices, then $det(AB) = det(A)*det(B)$

In [2]:
A = sy.MatrixSymbol("A", 2, 2)
B = sy.MatrixSymbol("B", 2, 2)

In [3]:
sy.Matrix(A).det() #* sy.Matrix(B).det()

A[0, 0]*A[1, 1] - A[0, 1]*A[1, 0]

In [4]:
sy.Matrix(A@B).det()

A[0, 0]*A[1, 1]*B[0, 0]*B[1, 1] - A[0, 0]*A[1, 1]*B[0, 1]*B[1, 0] - A[0, 1]*A[1, 0]*B[0, 0]*B[1, 1] + A[0, 1]*A[1, 0]*B[0, 1]*B[1, 0]

# Lecture 29: Laplace Expansion to Compute Determinant

In [5]:
A = np.array([[1, 0, 0, -1],
              [3, 0, 0, 5], 
              [2, 2, 4, 3],
              [1, 0, 5, 0]])
np.linalg.det(A)

79.99999999999997

In [6]:
sy.Matrix(A).det()

80

# Lecture 31: Properties of a Determinant 

**The determinant is a function that maps a square matrix to a scalar**.

## Three main properties:

- Property 1: $det(I) = 1$. 
- Property 2: determinant changes sign under row exchange.
- Property 3: determinant is a linear function of the first row, holding all other rows fixed. 

**Examples:**

- For property 2: $\begin{vmatrix} a & b \\ c & d \end{vmatrix} = - \begin{vmatrix} c & d \\ a & b \end{vmatrix}$.
- For property 3: $\begin{vmatrix} ka & kb \\ c & d \end{vmatrix} = k \begin{vmatrix} a & b \\ c & d \end{vmatrix}$ and $\begin{vmatrix} a + a^{'} & b + b^{'} \\ c & d \end{vmatrix} = \begin{vmatrix} a & b \\ c & d \end{vmatrix} + \begin{vmatrix} a^{'} & b^{'} \\ c & d \end{vmatrix}$.

## Other useful properties:

- The determinant is a linear function of any row, holding all other rows fixed.
- $det(A) = 0$ if $A$ has two equal rows.
- $det(A) = 0$ if $A$ has a row with all $0$'s. 
- $det(A) = 0$ if $A$ is singular or not invertible. 
- If we add $k$ times row-$i$ to row-$j$, the determinant doesn't change. *(Implies Gaussian elimination)*
- The determinant of a diagonal, upper and lower triangular matrix is the product of the diagonal elements.
- $det(AB) = det(A)det(B)$. 
- $det(A^{-1}) = \frac{1}{det(A)}$. 
- $det(A^{T}) = det(A)$.

**Proof of property 5:** 

**Question:** $\begin{vmatrix} a & b \\ c & d \end{vmatrix} = \begin{vmatrix} a + kc & b + kd \\ c & d \end{vmatrix}$ ?

**Answer:** $$\begin{vmatrix} a + kc & b + kd \\ c & d \end{vmatrix} = \begin{vmatrix} a & b \\ c & d \end{vmatrix} + \begin{vmatrix} kc & kd \\ c & d \end{vmatrix} = \begin{vmatrix} a & b \\ c & d \end{vmatrix} + k \begin{vmatrix} c & d \\ c & d \end{vmatrix} = \begin{vmatrix} a & b \\ c & d \end{vmatrix} + k \times 0 = \begin{vmatrix} a & b \\ c & d \end{vmatrix}$$. 

In [50]:
def GaussianElimination(mat): 
    """
    Calculate Gaussian elimination form of a square matrix A. 
    """
    
    n = mat.shape[0]
    A = mat.copy()
    
    for i in range(n):
        if i+1 < n:
            for j in range(i+1,n):
                factor = - A[j,i]/A[i,i]
                A[j,:] = A[j,:] +  factor*A[i,:]  
                
    
  
    return A

In [51]:
B = np.array([[2, 0, -1], 
              [3, 1, 1],
              [0, -1, 1]])
GaussianElimination(B)

array([[ 2,  0, -1],
       [ 0,  1,  2],
       [ 0,  0,  3]])

# Lecture 32: The Eigenvalue Problem

$$Ax = \lambda x$$
$$Ax = \lambda I x$$
$$(A - \lambda I)x = 0$$
**Characteristic euqation:**$$det(A - \lambda I) = 0$$
This turns out to be a $n^{th}$-order polynomial equation of $\lambda$.

# Lecture 33: Finding Eigenvalues and Eigenvectors 

In [55]:
A = np.array([[1, 1],
             [-1, 1]]) 
evals, evecs = np.linalg.eig(A)

In [56]:
evals

array([1.+1.j, 1.-1.j])

In [57]:
evecs

array([[0.70710678+0.j        , 0.70710678-0.j        ],
       [0.        +0.70710678j, 0.        -0.70710678j]])

# Lecture 35: Matrix Diagonalization

Let $A$ be a $n \times n$ matrix. We define $S$ to be the matrix whose columns are the eigenvectors of $A$. and $\Lambda$ to be the diagonal matrix with eigenvalues down the diagonal. Therefore, we have:
$$AS = S\Lambda$$
where $S$ is an invertible matrix. By multiplying $S^{-1}$ on both left and right sides of the equation, we have: 
$$\Lambda = S^{-1}AS$$
$$A = S\Lambda S^{-1}$$

In [85]:
A = sy.MatrixSymbol("A", 2, 2)
(S, D) = sy.Matrix(A).diagonalize()

In [86]:
S

Matrix([
[-2*A[0, 1]/(sqrt(A[0, 0]**2 - 2*A[0, 0]*A[1, 1] + 4*A[0, 1]*A[1, 0] + A[1, 1]**2) + A[0, 0] - A[1, 1]), 2*A[0, 1]/(sqrt(A[0, 0]**2 - 2*A[0, 0]*A[1, 1] + 4*A[0, 1]*A[1, 0] + A[1, 1]**2) - A[0, 0] + A[1, 1])],
[                                                                                                     1,                                                                                                     1]])

In [87]:
sy.Matrix(A)

Matrix([
[A[0, 0], A[0, 1]],
[A[1, 0], A[1, 1]]])

In [88]:
D

Matrix([
[-sqrt((A[0, 0] + A[1, 1])**2 - 4*A[0, 0]*A[1, 1] + 4*A[0, 1]*A[1, 0])/2 + A[0, 0]/2 + A[1, 1]/2,                                                                                              0],
[                                                                                              0, sqrt((A[0, 0] + A[1, 1])**2 - 4*A[0, 0]*A[1, 1] + 4*A[0, 1]*A[1, 0])/2 + A[0, 0]/2 + A[1, 1]/2]])

In [89]:
# A^{2}
sy.Matrix(A@A)

Matrix([
[     A[0, 0]**2 + A[0, 1]*A[1, 0], A[0, 0]*A[0, 1] + A[0, 1]*A[1, 1]],
[A[0, 0]*A[1, 0] + A[1, 0]*A[1, 1],      A[0, 1]*A[1, 0] + A[1, 1]**2]])

In [90]:
# SxD^{2}xS^{-1} 
sy.Matrix(S@D@D@S.inv())

Matrix([
[2*(-sqrt((A[0, 0] + A[1, 1])**2 - 4*A[0, 0]*A[1, 1] + 4*A[0, 1]*A[1, 0])/2 + A[0, 0]/2 + A[1, 1]/2)**2*A[0, 1]*A[1, 0]/((sqrt(A[0, 0]**2 - 2*A[0, 0]*A[1, 1] + 4*A[0, 1]*A[1, 0] + A[1, 1]**2) + A[0, 0] - A[1, 1])*sqrt(A[0, 0]**2 - 2*A[0, 0]*A[1, 1] + 4*A[0, 1]*A[1, 0] + A[1, 1]**2)) + 2*(sqrt((A[0, 0] + A[1, 1])**2 - 4*A[0, 0]*A[1, 1] + 4*A[0, 1]*A[1, 0])/2 + A[0, 0]/2 + A[1, 1]/2)**2*A[0, 1]*A[1, 0]/((sqrt(A[0, 0]**2 - 2*A[0, 0]*A[1, 1] + 4*A[0, 1]*A[1, 0] + A[1, 1]**2) - A[0, 0] + A[1, 1])*sqrt(A[0, 0]**2 - 2*A[0, 0]*A[1, 1] + 4*A[0, 1]*A[1, 0] + A[1, 1]**2)), -2*(-sqrt((A[0, 0] + A[1, 1])**2 - 4*A[0, 0]*A[1, 1] + 4*A[0, 1]*A[1, 0])/2 + A[0, 0]/2 + A[1, 1]/2)**2*(sqrt(A[0, 0]**2 - 2*A[0, 0]*A[1, 1] + 4*A[0, 1]*A[1, 0] + A[1, 1]**2)*A[0, 0] - sqrt(A[0, 0]**2 - 2*A[0, 0]*A[1, 1] + 4*A[0, 1]*A[1, 0] + A[1, 1]**2)*A[1, 1] + A[0, 0]**2 - 2*A[0, 0]*A[1, 1] + 2*A[0, 1]*A[1, 0] + A[1, 1]**2)*A[0, 1]/((sqrt(A[0, 0]**2 - 2*A[0, 0]*A[1, 1] + 4*A[0, 1]*A[1, 0] + A[1, 1]**2) + A[0, 0] - 

In [91]:
S.inv()

Matrix([
[-A[1, 0]/sqrt(A[0, 0]**2 - 2*A[0, 0]*A[1, 1] + 4*A[0, 1]*A[1, 0] + A[1, 1]**2), (sqrt(A[0, 0]**2 - 2*A[0, 0]*A[1, 1] + 4*A[0, 1]*A[1, 0] + A[1, 1]**2)*A[0, 0] - sqrt(A[0, 0]**2 - 2*A[0, 0]*A[1, 1] + 4*A[0, 1]*A[1, 0] + A[1, 1]**2)*A[1, 1] + A[0, 0]**2 - 2*A[0, 0]*A[1, 1] + 2*A[0, 1]*A[1, 0] + A[1, 1]**2)/(sqrt(A[0, 0]**2 - 2*A[0, 0]*A[1, 1] + 4*A[0, 1]*A[1, 0] + A[1, 1]**2)*A[0, 0] - sqrt(A[0, 0]**2 - 2*A[0, 0]*A[1, 1] + 4*A[0, 1]*A[1, 0] + A[1, 1]**2)*A[1, 1] + A[0, 0]**2 - 2*A[0, 0]*A[1, 1] + 4*A[0, 1]*A[1, 0] + A[1, 1]**2)],
[ A[1, 0]/sqrt(A[0, 0]**2 - 2*A[0, 0]*A[1, 1] + 4*A[0, 1]*A[1, 0] + A[1, 1]**2),                                                                                                                                                                                                                 2*A[0, 1]*A[1, 0]/(sqrt(A[0, 0]**2 - 2*A[0, 0]*A[1, 1] + 4*A[0, 1]*A[1, 0] + A[1, 1]**2)*A[0, 0] - sqrt(A[0, 0]**2 - 2*A[0, 0]*A[1, 1] + 4*A[0, 1]*A[1, 0] + A[1, 1]**2