In [1]:
import numpy as np 
import sympy as sy
from scipy.linalg import solve

# Lecture 16: Vector Spaces

# Lecture 17: Linear Independence

## Definition:

The vectors $ \{ u_1, u_2,...,u_n  \}$ are *linearly independent* if for any scalars $c_1,c_2,...,c_n$ the equation 
$$c_1u_1 + c_2u_2 + ... + c_nu_n = 0$$
has only solution $c_1=c_2=...=c_n=0$.

What this means is that one is unable to write any of the vectors $u_1,u_2,...,u_n$ as a linear combination of any of the other vectors.

## Method to check if a set of vectors are linearly independent:

If a set of vectors $ \{ u_1, u_2,...,u_n  \}$ are *linearly independent*, then the matrix $A = [u_1, u_2,...,u_n]$ is a full rank matrix.

In [2]:
# An example
#  A is a reduced rank matrix
A = np.array([[0, 1, 1],
              [1, 0, 0],
              [0, 1, 1]])

np.linalg.matrix_rank(A)

2

In [3]:
# Another example 
# A is a full rank matrix
A = np.array([[1, 1, 0],
              [1, 0, 1],
              [0, 1, 1]])

np.linalg.matrix_rank(A)

3

In [4]:
A = np.array([[2, -1, -1],
              [-1, 2, -1],
              [-1, -1, 2]])

np.linalg.matrix_rank(A)

2

# Lecture 18: Span,Basis and Dimension

# Lecture 19: Gram-Schmidt Process

![my diagram](diagram.svg)

**Purpose of Gram-Schmidt process:**

The purpose of Gram-Schmidt process is to make a set of vectors to be a orthonormal basis.

**The steps of Gram-Schmidt process:**

- We set $v_1$ as one of the basic vector.
- We then get $v_1^{T}(v_2 - \alpha v_1) = 0$, which we finally get $ \alpha = \frac{v_1^{T}v_2}{v_1^{T}v_1} $.
- Then, the $v_{2_{|| v_1}} = \frac{v_1^{T}v_2}{v_1^{T}v_1} v_1$.
- Finally, the $v_{2_{\perp v_1}} = v_2 - \frac{v_1^{T}v_2}{v_1^{T}v_1} v_1$.
- For $ v_{3_{\perp v_1,v_2}} = v_3 - \frac{v_1^{T}v_3}{v_1^{T}v_1} v_1 - \frac{v_{2_{\perp v_1}}^{T}v_3}{v_{2_{\perp v_1}}^{T}v_{2_{\perp v_1}}} v_{2_{\perp v_1}}  $


## QR decomposition

If $Q$ is not an orthogonal matrix originally, then Gram-Schmidt process cannot recover back to $A$, this is because there must have some information loss when doing the orthogonalization. To keep the information change, we will introduce a "residual" matrix $R$, which forms $A = QR$. This decomposition technique is called QR decomposition.

In [5]:
# An example
A = np.array([[1, 3],
              [1, 4]])
Q, R = np.linalg.qr(A)

In [6]:
Q

array([[-0.70710678, -0.70710678],
       [-0.70710678,  0.70710678]])

In [7]:
R

array([[-1.41421356, -4.94974747],
       [ 0.        ,  0.70710678]])

In [8]:
# Q is an orthonormal matrix
Q@Q.T

array([[ 1.00000000e+00, -1.33393446e-16],
       [-1.33393446e-16,  1.00000000e+00]])

# Lecture 21: Null Space

## Definition:
The null space of a matrix $A$, which we denote as $Null(A)$, is the vector space spanned by all column vectors $x$ that satisfy the matrix equation: 
$$Ax = 0$$

In [9]:
A = np.array([[-3, 6, -1, 1, -7],
              [1, -2, 2, 3, -1],
              [2, -4, 5, 8, -4]])
A

array([[-3,  6, -1,  1, -7],
       [ 1, -2,  2,  3, -1],
       [ 2, -4,  5,  8, -4]])

In [10]:
sy.Matrix(A).rref()[0]

Matrix([
[1, -2, 0, -1,  3],
[0,  0, 1,  2, -2],
[0,  0, 0,  0,  0]])

In [11]:
NA = np.array([[2, 1, -3],
               [1, 0, 0],
               [0, -2, 2],
               [0, 1, 0],
               [0, 0, 1]])

In [12]:
x = np.array([[1,1,-2,2,1]]).T

In [13]:
A@x

array([[0],
       [0],
       [0]])

When we find the $Null(A)$, we can then form the equation below:
$$A Null(A) y = 0$$
where $y$ is the vector of all *free variables*, which can take any value.

In [14]:
A@NA@np.array([[1,2,9]]).T

array([[0],
       [0],
       [0]])

In [15]:
# An example
A = np.array([[1, 1, 1, 0],
              [1, 1, 0, 1], 
              [1, 0, 1, 1]])
sy.Matrix(A).rref()[0]

Matrix([
[1, 0, 0,  2],
[0, 1, 0, -1],
[0, 0, 1, -1]])

In [16]:
A@np.array([[-2, 1, 1, 1]]).T

array([[0],
       [0],
       [0]])

# Lecture 22: Application of the Null Space

When the $A \in \mathcal{R}^{m\times n}$ and $m < n$, which means there are more unkowns than number of equations, we'd like to solve $Ax = b$, which is called underdetermined system of linear equations. 

Let $u$ be a general vector in $Null(A)$. Let $v$ be any vector that solves $Ax = b$. Then we can construct a general solution of $Ax = b$, which is $x = u+v$. This is because $Ax = A(u+v) = Au + Av = 0 + b = b$.

In [17]:
# An example
A = np.array([[2, 2, 1, 0],
              [2, -2, -1, 1]])
A

array([[ 2,  2,  1,  0],
       [ 2, -2, -1,  1]])

In [18]:
sy.Matrix(A).rref()[0]

Matrix([
[1, 0,   0,  1/4],
[0, 1, 1/2, -1/4]])

In [19]:
A = np.array([[-3, 6, -1, 1, -7],
              [1, -2, 2, 3, -1],
              [2, -4, 5, 8, -4]])
A

array([[-3,  6, -1,  1, -7],
       [ 1, -2,  2,  3, -1],
       [ 2, -4,  5,  8, -4]])

In [20]:
sy.Matrix(A).rref()[0]

Matrix([
[1, -2, 0, -1,  3],
[0,  0, 1,  2, -2],
[0,  0, 0,  0,  0]])

# Lecture 23: Column Space

**NOTE:** Reduced Row Echelon Form (RREF) doesn't change the linear dependency of columns of a matrix. 

In [21]:
# For example:
A = np.array([[-3, 6, -1, 1, -7],
              [1, -2, 2, 3, -1],
              [2, -4, 5, 8, -4]])
A

array([[-3,  6, -1,  1, -7],
       [ 1, -2,  2,  3, -1],
       [ 2, -4,  5,  8, -4]])

In [23]:
np.linalg.matrix_rank(A)

2

In [25]:
rref_A = sy.Matrix(A).rref()[0]
rref_A

Matrix([
[1, -2, 0, -1,  3],
[0,  0, 1,  2, -2],
[0,  0, 0,  0,  0]])

The `rref_A` has two pivot columns which are the first and the third columns. Therefore, the rank of the `rref_A` is $2$.

In [27]:
rref_A.rank()

2

In [28]:
A = np.array([[1, 1, 1, 0],
              [1, 1, 0, 1],
              [1, 0, 1, 1]])
A

array([[1, 1, 1, 0],
       [1, 1, 0, 1],
       [1, 0, 1, 1]])

In [29]:
sy.Matrix(A).rref()[0]

Matrix([
[1, 0, 0,  2],
[0, 1, 0, -1],
[0, 0, 1, -1]])

In [30]:
sy.Matrix(A).rank()

3

In [34]:
A = np.array([[2, 3, -1, 1, 2],
              [-1, -1, 0, -1, 1],
              [1, 2, -1, 1, 1],
              [1, -2, 3, -1, -3]])
A.T

array([[ 2, -1,  1,  1],
       [ 3, -1,  2, -2],
       [-1,  0, -1,  3],
       [ 1, -1,  1, -1],
       [ 2,  1,  1, -3]])

In [33]:
sy.Matrix(A.T).rref()[0]

Matrix([
[1, 0, 0,  2],
[0, 1, 0, -2],
[0, 0, 1, -5],
[0, 0, 0,  0],
[0, 0, 0,  0]])

# Lecture 24: Row Space, Left Null Space and Rank

If $A \in \mathcal{R}^{m \times n}:$

- $Null(A)$: subspace of all vectors in $\mathcal{R}^{n}$. 
- $Col(A)$: subspace of all vectors in $\mathcal{R}^{m}$.
- $Row(A) = Col(A^{T})$: subspace of all vectors in $\mathcal{R}^{n}$.
- $LeftNull(A) = Null(A^{T})$: subspace of all vectors in $\mathcal{R}^{m}$. 

After RREF, the $dim(Null(A)) = $ number of non-pivot columns. The $dim(Row(A)) = $ number of pivot columns. Therefore, $Null(A)$ and $Row(A)$ are orthogonal complements, and $LeftNull(A)$ and $Col(A)$ are orthogonal complements.

In [35]:
A = np.array([[1, 2, 0, 1],
              [2, 4, 1, 1], 
              [3, 6, 1, 1]])
sy.Matrix(A).rref()[0]

Matrix([
[1, 2, 0, 0],
[0, 0, 1, 0],
[0, 0, 0, 1]])

In [36]:
sy.Matrix(A).rank()

3

# Lecture 27: Solution of Least-Square Problem  

**Normal equation:**

$$A^{T}Ax = A^{T}b$$

**Solution of least-square problem:**
$$(A^{T}A)^{-1}A^{T}Ax = x = (A^{T}A)^{-1}A^{T}b$$

**Projection matrix:**
$$Ax = A(A^{T}A)^{-1}A^{T}b$$
where $A(A^{T}A)^{-1}A^{T}$ is called *projection matrix*.

In [38]:
A = np.array([[4, 6, 11],
              [6, 14, 21]])
sy.Matrix(A).rref()[0]

Matrix([
[1, 0,  7/5],
[0, 1, 9/10]])

In [39]:
A = np.array([[1, 0, 3], 
              [-3, -1, 2],
              [4, 1, 1]])
sy.Matrix(A).rref()[0]

Matrix([
[1, 0,   3],
[0, 1, -11],
[0, 0,   0]])

In [40]:
sy.Matrix(A).rank()

2

In [45]:
A = np.array([[1, 1, 3],
              [1, -4, 2],
              [0, 5, 1]])
sy.Matrix(A).rref()[0]

Matrix([
[1, 0, 14/5],
[0, 1,  1/5],
[0, 0,    0]])

In [42]:
sy.Matrix(A).rank()

3

In [43]:
A = np.array([[1, -1, 1, 1],
              [4, -4, 3, 6],
              [2, -2, 1, 3]])
sy.Matrix(A).rref()[0]

Matrix([
[1, -1, 0, 0],
[0,  0, 1, 0],
[0,  0, 0, 1]])

In [47]:
A = np.array([[1, -2, 0, 1],
              [2, -4, 1, 2],
              [3, -6, 1, 3]])
sy.Matrix(A).rref()[0]

Matrix([
[1, -2, 0, 1],
[0,  0, 1, 0],
[0,  0, 0, 0]])