In [70]:
import numpy as np
import sympy as sy 
from scipy import linalg

# Lecture 10: Gaussian Elimination

# Lecture 11: Reduced Row Echelon Form (RREF)

In [7]:
A = sy.MatrixSymbol("A", 3, 4)
sy.Matrix(A)

Matrix([
[A[0, 0], A[0, 1], A[0, 2], A[0, 3]],
[A[1, 0], A[1, 1], A[1, 2], A[1, 3]],
[A[2, 0], A[2, 1], A[2, 2], A[2, 3]]])

In [9]:
sy.Matrix(A).rref()[0]

Matrix([
[1, 0, 0,  (A[0, 1]*A[1, 2]*A[2, 3] - A[0, 1]*A[1, 3]*A[2, 2] - A[0, 2]*A[1, 1]*A[2, 3] + A[0, 2]*A[1, 3]*A[2, 1] + A[0, 3]*A[1, 1]*A[2, 2] - A[0, 3]*A[1, 2]*A[2, 1])/(A[0, 0]*A[1, 1]*A[2, 2] - A[0, 0]*A[1, 2]*A[2, 1] - A[0, 1]*A[1, 0]*A[2, 2] + A[0, 1]*A[1, 2]*A[2, 0] + A[0, 2]*A[1, 0]*A[2, 1] - A[0, 2]*A[1, 1]*A[2, 0])],
[0, 1, 0, (-A[0, 0]*A[1, 2]*A[2, 3] + A[0, 0]*A[1, 3]*A[2, 2] + A[0, 2]*A[1, 0]*A[2, 3] - A[0, 2]*A[1, 3]*A[2, 0] - A[0, 3]*A[1, 0]*A[2, 2] + A[0, 3]*A[1, 2]*A[2, 0])/(A[0, 0]*A[1, 1]*A[2, 2] - A[0, 0]*A[1, 2]*A[2, 1] - A[0, 1]*A[1, 0]*A[2, 2] + A[0, 1]*A[1, 2]*A[2, 0] + A[0, 2]*A[1, 0]*A[2, 1] - A[0, 2]*A[1, 1]*A[2, 0])],
[0, 0, 1,  (A[0, 0]*A[1, 1]*A[2, 3] - A[0, 0]*A[1, 3]*A[2, 1] - A[0, 1]*A[1, 0]*A[2, 3] + A[0, 1]*A[1, 3]*A[2, 0] + A[0, 3]*A[1, 0]*A[2, 1] - A[0, 3]*A[1, 1]*A[2, 0])/(A[0, 0]*A[1, 1]*A[2, 2] - A[0, 0]*A[1, 2]*A[2, 1] - A[0, 1]*A[1, 0]*A[2, 2] + A[0, 1]*A[1, 2]*A[2, 0] + A[0, 2]*A[1, 0]*A[2, 1] - A[0, 2]*A[1, 1]*A[2, 0])]])

In [12]:
# An example
A = np.array([[3, -7, -2, -7], 
              [-3, 5, 1, 5],
              [6, -4, 0, 2]])
sy.Matrix(A).rref()[0]

Matrix([
[1, 0, 0,  3],
[0, 1, 0,  4],
[0, 0, 1, -6]])

In [16]:
# Another example
B = np.array([[1, 2, 1], 
              [2, 4, 1], 
              [3, 6, 2]])
sy.Matrix(B).rref()[0]

Matrix([
[1, 2, 0],
[0, 0, 1],
[0, 0, 0]])

# Lecture 12: Computing Inverses

Refer to 6.1 in week 1

In [18]:
A = sy.MatrixSymbol("A", 3, 3)
sy.Matrix(A)

Matrix([
[A[0, 0], A[0, 1], A[0, 2]],
[A[1, 0], A[1, 1], A[1, 2]],
[A[2, 0], A[2, 1], A[2, 2]]])

In [22]:
Augmented = sy.Matrix(np.hstack((A, np.eye(3))))
Augmented

Matrix([
[A[0, 0], A[0, 1], A[0, 2], 1.0,   0,   0],
[A[1, 0], A[1, 1], A[1, 2],   0, 1.0,   0],
[A[2, 0], A[2, 1], A[2, 2],   0,   0, 1.0]])

In [23]:
Augmented.rref()[0]

Matrix([
[1, 0, 0,  (1.0*A[1, 1]*A[2, 2] - 1.0*A[1, 2]*A[2, 1])/(1.0*A[0, 0]*A[1, 1]*A[2, 2] - 1.0*A[0, 0]*A[1, 2]*A[2, 1] - 1.0*A[0, 1]*A[1, 0]*A[2, 2] + 1.0*A[0, 1]*A[1, 2]*A[2, 0] + 1.0*A[0, 2]*A[1, 0]*A[2, 1] - 1.0*A[0, 2]*A[1, 1]*A[2, 0]), (-1.0*A[0, 1]*A[2, 2] + 1.0*A[0, 2]*A[2, 1])/(1.0*A[0, 0]*A[1, 1]*A[2, 2] - 1.0*A[0, 0]*A[1, 2]*A[2, 1] - 1.0*A[0, 1]*A[1, 0]*A[2, 2] + 1.0*A[0, 1]*A[1, 2]*A[2, 0] + 1.0*A[0, 2]*A[1, 0]*A[2, 1] - 1.0*A[0, 2]*A[1, 1]*A[2, 0]),  (1.0*A[0, 1]*A[1, 2] - 1.0*A[0, 2]*A[1, 1])/(1.0*A[0, 0]*A[1, 1]*A[2, 2] - 1.0*A[0, 0]*A[1, 2]*A[2, 1] - 1.0*A[0, 1]*A[1, 0]*A[2, 2] + 1.0*A[0, 1]*A[1, 2]*A[2, 0] + 1.0*A[0, 2]*A[1, 0]*A[2, 1] - 1.0*A[0, 2]*A[1, 1]*A[2, 0])],
[0, 1, 0, (-1.0*A[1, 0]*A[2, 2] + 1.0*A[1, 2]*A[2, 0])/(1.0*A[0, 0]*A[1, 1]*A[2, 2] - 1.0*A[0, 0]*A[1, 2]*A[2, 1] - 1.0*A[0, 1]*A[1, 0]*A[2, 2] + 1.0*A[0, 1]*A[1, 2]*A[2, 0] + 1.0*A[0, 2]*A[1, 0]*A[2, 1] - 1.0*A[0, 2]*A[1, 1]*A[2, 0]),  (1.0*A[0, 0]*A[2, 2] - 1.0*A[0, 2]*A[2, 0])/(1.0*A[0, 0]*A[1, 1]*

In [26]:
# An example
A = np.array([[3, -7, -2],
              [-3, 5, 1],
              [6, -4, 0]])
B = np.hstack((A, np.eye(3)))
B

array([[ 3., -7., -2.,  1.,  0.,  0.],
       [-3.,  5.,  1.,  0.,  1.,  0.],
       [ 6., -4.,  0.,  0.,  0.,  1.]])

In [27]:
sy.Matrix(B)

Matrix([
[ 3.0, -7.0, -2.0, 1.0,   0,   0],
[-3.0,  5.0,  1.0,   0, 1.0,   0],
[ 6.0, -4.0,    0,   0,   0, 1.0]])

In [28]:
sy.Matrix(B).rref()[0]

Matrix([
[1, 0, 0, 0.666666666666667, 1.33333333333333,  0.5],
[0, 1, 0,               1.0,              2.0,  0.5],
[0, 0, 1,              -3.0,             -5.0, -1.0]])

# Lecture 13: Elementary Matrices

# Lecture 14: LU Decomposition

$$M_{3}M_{2}M_{1}A = U$$
$$ A = M_{1}^{-1}M_{2}^{-1}M_{3}^{-1}U $$
where $L = M_{1}^{-1}M_{2}^{-1}M_{3}^{-1}$, then,
$$ A = LU $$


In [29]:
A = np.array([[1, 0, 0],
              [2, 1, 0],
              [-1, -1, 1]])
A

array([[ 1,  0,  0],
       [ 2,  1,  0],
       [-1, -1,  1]])

In [31]:
np.linalg.inv(A)

array([[ 1.,  0.,  0.],
       [-2.,  1., -0.],
       [-1.,  1.,  1.]])

In [63]:
# an example
B = np.array([[-3, 2, -1],
              [6, -6, 7],
              [3, -4, 4]])

In [60]:
L,U = linalg.lu(B, permute_l=True)

In [61]:
L

array([[-0.5,  1. ,  0. ],
       [ 1. ,  0. ,  0. ],
       [ 0.5,  1. ,  1. ]])

In [62]:
U

array([[ 6. , -6. ,  7. ],
       [ 0. , -1. ,  2.5],
       [ 0. ,  0. , -2. ]])

In [67]:
# another example
A = np.array([[3, -7, -2],
              [-3, 5, 1],
              [6, -4, 0]])

P,L,U = linalg.lu(A)

In [68]:
L

array([[ 1. ,  0. ,  0. ],
       [ 0.5,  1. ,  0. ],
       [-0.5, -0.6,  1. ]])

In [69]:
U

array([[ 6. , -4. ,  0. ],
       [ 0. , -5. , -2. ],
       [ 0. ,  0. , -0.2]])