In [10]:
import numpy as np 
import sympy as sy

# Lecture 16: Vector Spaces

# Lecture 17: Linear Independence

## Definition:

The vectors $ \{ u_1, u_2,...,u_n  \}$ are *linearly independent* if for any scalars $c_1,c_2,...,c_n$ the equation 
$$c_1u_1 + c_2u_2 + ... + c_nu_n = 0$$
has only solution $c_1=c_2=...=c_n=0$.

What this means is that one is unable to write any of the vectors $u_1,u_2,...,u_n$ as a linear combination of any of the other vectors.

## Method to check if a set of vectors are linearly independent:

If a set of vectors $ \{ u_1, u_2,...,u_n  \}$ are *linearly independent*, then the matrix $A = [u_1, u_2,...,u_n]$ is a full rank matrix.

In [2]:
# An example
#  A is a reduced rank matrix
A = np.array([[0, 1, 1],
              [1, 0, 0],
              [0, 1, 1]])

np.linalg.matrix_rank(A)

2

In [3]:
# Another example 
# A is a full rank matrix
A = np.array([[1, 1, 0],
              [1, 0, 1],
              [0, 1, 1]])

np.linalg.matrix_rank(A)

3

In [4]:
A = np.array([[2, -1, -1],
              [-1, 2, -1],
              [-1, -1, 2]])

np.linalg.matrix_rank(A)

2

# Lecture 18: Span,Basis and Dimension

# Lecture 19: Gram-Schmidt Process

![my diagram](diagram.svg)

**Purpose of Gram-Schmidt process:**

The purpose of Gram-Schmidt process is to make a set of vectors to be a orthonormal basis.

**The steps of Gram-Schmidt process:**

- We set $v_1$ as one of the basic vector.
- We then get $v_1^{T}(v_2 - \alpha v_1) = 0$, which we finally get $ \alpha = \frac{v_1^{T}v_2}{v_1^{T}v_1} $.
- Then, the $v_{2_{|| v_1}} = \frac{v_1^{T}v_2}{v_1^{T}v_1} v_1$.
- Finally, the $v_{2_{\perp v_1}} = v_2 - \frac{v_1^{T}v_2}{v_1^{T}v_1} v_1$.
- For $ v_{3_{\perp v_1,v_2}} = v_3 - \frac{v_1^{T}v_3}{v_1^{T}v_1} v_1 - \frac{v_{2_{\perp v_1}}^{T}v_3}{v_{2_{\perp v_1}}^{T}v_{2_{\perp v_1}}} v_{2_{\perp v_1}}  $


## QR decomposition

If $Q$ is not an orthogonal matrix originally, then Gram-Schmidt process cannot recover back to $A$, this is because there must have some information loss when doing the orthogonalization. To keep the information change, we will introduce a "residual" matrix $R$, which forms $A = QR$. This decomposition technique is called QR decomposition.

In [13]:
# An example
A = np.array([[1, 3],
              [1, 4]])
Q, R = np.linalg.qr(A)

In [14]:
Q

array([[-0.70710678, -0.70710678],
       [-0.70710678,  0.70710678]])

In [15]:
R

array([[-1.41421356, -4.94974747],
       [ 0.        ,  0.70710678]])

In [16]:
# Q is an orthonormal matrix
Q@Q.T

array([[ 1.00000000e+00, -1.33393446e-16],
       [-1.33393446e-16,  1.00000000e+00]])